### ISSUE TITLE
Uberspace mag FollowSymlinks nicht.

### ISSUE THREAD

**Issue by tatome** [JonasGroeger/flask-uberspace-quickstart#3]
Die .htaccess - Datei enthält die Option "FollowSymlinks".  Wenn ich die so ins html-Verzeichnis lege, bekomme ich eine entsprechende Nachricht von Uberspace und die Datei wird automatisch gepatcht (funktioniert dann aber immer noch nicht).  Wenn ich beide Vorkommen der Option entferne, geht meine Anwendung.

https://wiki.uberspace.de/faq#options_followsymlinks_und_damit_auch_options_all_in_der_htaccess_funktioniert_nicht

**Comment by rajanski** [comment]
Hab grade nen pull request dafür gestartet https://github.com/JonasGroeger/flask-uberspace-quickstart/pull/4
